name: hospirent
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.3.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.20.2
  icons_plus: ^5.0.0
  lottie: ^3.3.1
  shared_preferences: ^2.3.0
  iconsax_flutter: ^1.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
          - family: PoppinsRegular
            fonts:
              - asset: assets/fonts/Poppins-Regular.ttf

          - family: PoppinsSemiBold
            fonts:
               - asset: assets/fonts/Poppins-SemiBold.ttf
          - family: PoppinsMedium
            fonts:
              - asset: assets/fonts/Poppins-Medium.ttf
          - family: PoppinsBold
            fonts:
              - asset: assets/fonts/Poppins-Bold.ttf


